version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: congestion-service-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: congestion
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: congestion-service
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/congestion
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_SQL_INIT_MODE: always
      SPRING_SQL_INIT_DATA_LOCATIONS: classpath:data.sql
#      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true
    ports:
      - "8080:8080"
    networks:
      - internal

volumes:
  pgdata:

networks:
  internal:
    driver: bridge

